// ===== 商品数据库 =====
const products = [
    // 电子产品
    {
        id: 1,
        name: "Apple iPhone 16 Pro Max 256GB 原色钛金属",
        subtitle: "A18 Pro芯片 | 4800万像素主摄 | USB-C接口",
        category: "electronics",
        categoryName: "数码电器",
        price: 9999,
        originalPrice: 13999,
        discount: 29,
        rating: 4.9,
        reviews: 12580,
        icon: "fa-mobile-screen-button",
        color: "#1a1a2e",
        badge: "爆款",
        features: ["A18 Pro芯片，性能飞跃", "4800万像素超清摄影系统", "USB-C快充接口", "全天候电池续航"]
    },
    {
        id: 2,
        name: "MacBook Air M3 笔记本电脑 15英寸 午夜色",
        subtitle: "M3芯片 | 16GB内存 | 512GB固态硬盘",
        category: "electronics",
        categoryName: "数码电器",
        price: 10499,
        originalPrice: 12999,
        discount: 19,
        rating: 4.8,
        reviews: 8920,
        icon: "fa-laptop",
        color: "#2d2d44",
        badge: "新品",
        features: ["Apple M3芯片", "15.3英寸Liquid视网膜屏", "18小时超长续航", "无风扇静音设计"]
    },
    {
        id: 3,
        name: "Sony WH-1000XM5 头戴式无线降噪耳机 黑色",
        subtitle: "行业领先降噪 | 30小时续航 | Hi-Res音质",
        category: "electronics",
        categoryName: "数码电器",
        price: 2299,
        originalPrice: 2999,
        discount: 23,
        rating: 4.7,
        reviews: 15600,
        icon: "fa-headphones",
        color: "#16213e",
        badge: "特价",
        features: ["30小时超长续航", "行业领先降噪技术", "Hi-Res高解析音质", "多点连接"]
    },
    {
        id: 4,
        name: "Samsung Galaxy S24 Ultra 12+512GB 钛灰",
        subtitle: "Galaxy AI | 2亿像素 | S Pen内置",
        category: "electronics",
        categoryName: "数码电器",
        price: 9699,
        originalPrice: 11999,
        discount: 19,
        rating: 4.8,
        reviews: 7340,
        icon: "fa-tablet-screen-button",
        color: "#1b1b2f",
        badge: "",
        features: ["Snapdragon 8 Gen 3", "2亿像素主摄", "Galaxy AI智能功能", "S Pen手写笔"]
    },
    {
        id: 5,
        name: "iPad Pro M4 平板电脑 11英寸 WiFi 256GB",
        subtitle: "Ultra Retina XDR显示屏 | Apple Pencil Pro",
        category: "electronics",
        categoryName: "数码电器",
        price: 7999,
        originalPrice: 8999,
        discount: 11,
        rating: 4.9,
        reviews: 5620,
        icon: "fa-tablet-alt",
        color: "#0f3460",
        badge: "热销",
        features: ["M4芯片强劲性能", "Ultra Retina XDR屏幕", "Apple Pencil Pro支持", "超薄一体化设计"]
    },
    {
        id: 6,
        name: "DJI Mini 4 Pro 航拍无人机 畅飞套装",
        subtitle: "249g轻巧机身 | 4K HDR视频 | 全向避障",
        category: "electronics",
        categoryName: "数码电器",
        price: 5788,
        originalPrice: 6988,
        discount: 17,
        rating: 4.6,
        reviews: 3210,
        icon: "fa-helicopter",
        color: "#1a1a2e",
        badge: "",
        features: ["249g轻量设计无需登记", "4K/60fps HDR视频", "全向障碍物感应", "34分钟续航"]
    },
    // 服装鞋包
    {
        id: 7,
        name: "Nike Air Max 270 男子运动鞋 黑白配色",
        subtitle: "Air Max气垫 | 透气网面 | 缓震回弹",
        category: "clothing",
        categoryName: "时尚服饰",
        price: 899,
        originalPrice: 1299,
        discount: 31,
        rating: 4.6,
        reviews: 23450,
        icon: "fa-shoe-prints",
        color: "#e94560",
        badge: "特价",
        features: ["Air Max 270气垫", "工程网眼鞋面", "泡棉中底", "橡胶外底"]
    },
    {
        id: 8,
        name: "Uniqlo 优衣库 男女同款轻型羽绒服",
        subtitle: "650蓬松度 | 可收纳设计 | 多色可选",
        category: "clothing",
        categoryName: "时尚服饰",
        price: 399,
        originalPrice: 599,
        discount: 33,
        rating: 4.5,
        reviews: 45600,
        icon: "fa-vest",
        color: "#073b4c",
        badge: "爆款",
        features: ["650蓬松度羽绒", "轻便可收纳", "防泼水面料", "多色可选"]
    },
    {
        id: 9,
        name: "Adidas Ultraboost 23 男子跑步鞋 Core Black",
        subtitle: "Boost中底 | Primeknit鞋面 | Continental大底",
        category: "clothing",
        categoryName: "时尚服饰",
        price: 1099,
        originalPrice: 1690,
        discount: 35,
        rating: 4.7,
        reviews: 18900,
        icon: "fa-shoe-prints",
        color: "#16213e",
        badge: "",
        features: ["BOOST能量回馈", "Primeknit编织鞋面", "Continental马牌橡胶", "Torsion系统"]
    },
    {
        id: 10,
        name: "COACH Tabby 经典手提包 黑色",
        subtitle: "意大利牛皮 | 标志性压花 | 可斜挎",
        category: "clothing",
        categoryName: "时尚服饰",
        price: 2590,
        originalPrice: 3580,
        discount: 28,
        rating: 4.8,
        reviews: 5670,
        icon: "fa-bag-shopping",
        color: "#2d3436",
        badge: "轻奢",
        features: ["意大利进口牛皮", "经典Tabby设计", "可调节肩带", "拉链开合"]
    },
    // 家居生活
    {
        id: 11,
        name: "Dyson V15 Detect 无线吸尘器 金色",
        subtitle: "激光探测 | 压电式传感器 | 60分钟续航",
        category: "home",
        categoryName: "家居生活",
        price: 4990,
        originalPrice: 5990,
        discount: 17,
        rating: 4.8,
        reviews: 12340,
        icon: "fa-wind",
        color: "#e17055",
        badge: "旗舰",
        features: ["激光探测微尘", "压电式传感器计数", "60分钟续航", "整机HEPA过滤"]
    },
    {
        id: 12,
        name: "MUJI 无印良品 懒人沙发 米色 大号",
        subtitle: "记忆棉填充 | 可拆洗外套 | 舒适坐感",
        category: "home",
        categoryName: "家居生活",
        price: 890,
        originalPrice: 1290,
        discount: 31,
        rating: 4.5,
        reviews: 8760,
        icon: "fa-couch",
        color: "#fdcb6e",
        badge: "",
        features: ["高密度记忆棉", "可拆洗外套", "人体工学设计", "多色可选"]
    },
    {
        id: 13,
        name: "Philips 飞利浦 智能LED台灯 昼光版",
        subtitle: "调光调色 | 护眼模式 | 定时休息提醒",
        category: "home",
        categoryName: "家居生活",
        price: 459,
        originalPrice: 699,
        discount: 34,
        rating: 4.6,
        reviews: 15430,
        icon: "fa-lightbulb",
        color: "#ffeaa7",
        badge: "特价",
        features: ["5500K模拟自然光", "无频闪护眼", "智能调光调色", "USB充电接口"]
    },
    {
        id: 14,
        name: "小米米家 扫地机器人Pro 激光导航 拖扫一体",
        subtitle: "LDS激光导航 | 5000Pa吸力 | 自动集尘",
        category: "home",
        categoryName: "家居生活",
        price: 2699,
        originalPrice: 3499,
        discount: 23,
        rating: 4.7,
        reviews: 21560,
        icon: "fa-robot",
        color: "#dfe6e9",
        badge: "智能",
        features: ["LDS激光导航建图", "5000Pa强劲吸力", "自动集尘底座", "APP远程控制"]
    },
    // 运动户外
    {
        id: 15,
        name: "Garmin Forerunner 265 GPS运动手表 黑白色",
        subtitle: "AMOLED彩屏 | 训练状态 | 续航13天",
        category: "sports",
        categoryName: "运动户外",
        price: 3680,
        originalPrice: 4280,
        discount: 14,
        rating: 4.8,
        reviews: 6780,
        icon: "fa-stopwatch",
        color: "#2d3436",
        badge: "",
        features: ["1.3寸AMOLED屏幕", "训练状态&恢复时间", "GPS+多卫星系统", "13天超长续航"]
    },
    {
        id: 16,
        name: "Coleman 科勒曼 自动速开帐篷 四人款",
        subtitle: "60秒快速搭建 | 防雨涂层 | 遮阳顶棚",
        category: "sports",
        categoryName: "运动户外",
        price: 1299,
        originalPrice: 1899,
        discount: 32,
        rating: 4.5,
        reviews: 4320,
        icon: "fa-campground",
        color: "#00b894",
        badge: "户外",
        features: ["60秒快速搭建", "TX2防雨技术", "可拆卸遮阳顶棚", "电线管理口"]
    },
    {
        id: 17,
        name: "Keep 智能健身镜 家用全能健身房",
        subtitle: "AI动作识别 | 实时课程 | 4K高清屏",
        category: "sports",
        categoryName: "运动户外",
        price: 2999,
        originalPrice: 3999,
        discount: 25,
        rating: 4.4,
        reviews: 3210,
        icon: "fa-dumbbell",
        color: "#636e72",
        badge: "新品",
        features: ["43寸4K高清屏", "AI动作实时纠正", "500+在线课程", "镜面模式隐藏"]
    },
    // 美妆个护
    {
        id: 18,
        name: "SK-II 神仙水护肤精华露 230ml",
        subtitle: "PITERA™精华 | 改善肌肤质地 | 经典畅销",
        category: "beauty",
        categoryName: "美妆个护",
        price: 1190,
        originalPrice: 1590,
        discount: 25,
        rating: 4.8,
        reviews: 34560,
        icon: "fa-spray-can-sparkles",
        color: "#fd79a8",
        badge: "爆款",
        features: ["90%以上PITERA™精华", "改善肌肤五大维度", "清爽不黏腻", "全球畅销经典"]
    },
    {
        id: 19,
        name: "戴森 Supersonic HD08 吹风机 镍金色",
        subtitle: "高速数码马达 | 智能温控 | 负离子护发",
        category: "beauty",
        categoryName: "美妆个护",
        price: 2790,
        originalPrice: 3390,
        discount: 18,
        rating: 4.7,
        reviews: 18900,
        icon: "fa-wind",
        color: "#e17055",
        badge: "",
        features: ["高速数码马达", "智能温控防护", "附赠4款风嘴", "轻量化设计"]
    },
    {
        id: 20,
        name: "雅诗兰黛 小棕瓶精华露 第七代 100ml",
        subtitle: "肌因修护 | 抗老紧致 | 夜间修护",
        category: "beauty",
        categoryName: "美妆个护",
        price: 980,
        originalPrice: 1380,
        discount: 29,
        rating: 4.7,
        reviews: 28700,
        icon: "fa-pump-soap",
        color: "#2d3436",
        badge: "经典",
        features: ["第七代配方升级", "ChronoluxCB™技术", "夜间密集修护", "100ml大容量"]
    }
];

// ===== 轮播图数据 =====
const slides = [
    {
        title: "夏日狂欢节",
        subtitle: "精选好物低至3折起",
        gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        cta: "立即抢购"
    },
    {
        title: "新品首发",
        subtitle: "最新科技产品抢先体验",
        gradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
        cta: "查看详情"
    },
    {
        title: "品牌特卖",
        subtitle: "大牌正品，超值优惠",
        gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
        cta: "马上选购"
    }
];
